minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@layerwise/vite'

overrides:
  rolldown: 1.2.10
  baseline-browser-mapping: 2.11.25
  browserslist: 4.29.0
  caniuse-lite: 1.0.30001810
  electron-to-chromium: 1.5.438

allowBuilds:
  esbuild: true
  workerd: true
